import { AppSettings } from '../hooks/useSettings'

interface Props {
  settings: AppSettings
  onUpdate: (patch: Partial<AppSettings>) => void
}

function Toggle({ on, onChange, label, description }: {
  on: boolean
  onChange: (v: boolean) => void
  label: string
  description: string
}) {
  return (
    <div
      style={{
        display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
        gap: 16, padding: '14px 0', borderBottom: '1px solid var(--border)',
      }}
    >
      <div>
        <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text)', marginBottom: 4 }}>{label}</div>
        <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>{description}</div>
      </div>
      <button
        onClick={() => onChange(!on)}
        style={{
          flexShrink: 0,
          width: 44, height: 24, borderRadius: 12,
          background: on ? 'var(--accent)' : 'var(--surface2)',
          border: 'none', cursor: 'pointer', position: 'relative',
          transition: 'background 0.2s',
          padding: 0,
        }}
        title={on ? 'Click to disable' : 'Click to enable'}
      >
        <span style={{
          position: 'absolute',
          top: 3, left: on ? 23 : 3,
          width: 18, height: 18, borderRadius: '50%',
          background: '#fff',
          transition: 'left 0.2s',
          boxShadow: '0 1px 3px rgba(0,0,0,.3)',
        }} />
      </button>
    </div>
  )
}

export function SettingsTab({ settings, onUpdate }: Props) {
  return (
    <div>
      <div className="card">
        <div className="card-title">Transcription</div>

        <Toggle
          on={settings.autoTranscribe}
          onChange={v => onUpdate({ autoTranscribe: v })}
          label="Auto-transcribe after saving"
          description={
            settings.autoTranscribe
              ? 'After each recording is saved, it will automatically be sent to Deepgram for transcription. You can then view word-timed lyrics from the Recordings tab.'
              : 'Transcription is manual. After saving a recording, go to the Recordings tab and click 🎤 Lyrics → ✦ Transcribe to generate a transcript.'
          }
        />

        <div style={{ paddingTop: 14, fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.7 }}>
          <strong style={{ color: 'var(--text)' }}>About transcription</strong><br />
          Transcripts are generated by{' '}
          <span style={{ color: 'var(--accent)' }}>Deepgram nova-3</span> with word-level
          timestamps, smart formatting, and punctuation. Each transcript is stored alongside
          the recording file and enables Spotify-style word highlighting during playback.
        </div>
      </div>

      <div className="card" style={{ marginTop: 16 }}>
        <div className="card-title">Storage</div>
        <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.8 }}>
          <div>Recordings are saved on the server as <code style={{ color: 'var(--cyan)' }}>.webm</code> files (WebM/Opus)</div>
          <div>Transcripts are saved as <code style={{ color: 'var(--cyan)' }}>.transcript.json</code> alongside each recording</div>
          <div>Settings are stored locally in your browser (localStorage)</div>
        </div>
      </div>
    </div>
  )
}
